server:
  servlet:
    context-path: /supershop

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geek_shop?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geek
    password: geek
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
