server:
  servlet:
    context-path: /supershop

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/geek_shop?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/geek_shop?useUnicode=true&characterEncoding=utf8
#
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geek
    password: geek
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false

files:
  storepath:
#    icons:  "//Users//admin//Desktop//учеба//Spring//Spring2//HW//view//icons"
    icons:  "E:\\учеба\\Основы веб-разработки на Spring Framework\\Spring2\\view\\icons"
#    images: "//Users//admin//Desktop//учеба//Spring//Spring2//HW//view//images"
    images: "E:\\учеба\\Основы веб-разработки на Spring Framework\\Spring2\\view\\images"
#    reviewImages: "E:\\учеба\\Основы веб-разработки на Spring Framework\\Spring2\\view\\review_images"


